sudo: false

language: node_js

node_js:
  - stable

before_install:
  - npm install -g npm
  - npm install -g gulp

before_script:  
# Special config for Chrome on Travis-CI
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script:
  - gulp travis-ci

# Disable email notifications
notifications:  
  email: false